<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net472;net6.0;net8.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="NUnit" Version="4.2.2" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataMatrix.Core\DataMatrix.Core.csproj" />
	</ItemGroup>
</Project>
